# Generated by Django 5.2.5 on 2026-05-18 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_projectimage_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title (French)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_fr', models.TextField(verbose_name='Description (French)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Main Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studio.project')),
            ],
        ),
    ]
