# Generated by Django 5.2.5 on 2026-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base Price'),
            preserve_default=False,
        ),
    ]
