# Generated by Django 5.2.5 on 2026-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_service_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking',
            field=models.BooleanField(default=True, verbose_name='can book it'),
        ),
    ]
