# Generated by Django 5.2.5 on 2026-04-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
