# Generated by Django 5.2.5 on 2026-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_creted_at_productattribute_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Icon Image'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount %'),
        ),
    ]
