# Generated by Django 5.2.5 on 2026-05-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_productcategory_icon_storecategory_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text_ar',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text_en',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text_fr',
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text'),
        ),
    ]
