# Generated by Django 5.2.5 on 2026-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_cart_cartitem_customeraddress_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='stores.productattribute', verbose_name='Selected Attributes'),
        ),
    ]
