# Generated by Django 5.2.5 on 2026-06-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_cartitem_options_remove_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=225, unique=True, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(max_length=225, verbose_name='Name (AR)')),
                ('name_fr', models.CharField(max_length=225, verbose_name='Name (FR)')),
                ('logo', models.ImageField(upload_to='delivery_companies/')),
                ('website', models.URLField(blank=True)),
                ('tracking_url', models.URLField(blank=True)),
                ('api_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Company',
                'verbose_name_plural': 'Delivery Companies',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='img/logo.png', upload_to='products/main/', verbose_name='Main Image'),
        ),
        migrations.CreateModel(
            name='StoreDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Price')),
                ('free_delivery_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Free Delivery From')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.deliverycompany')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_companies', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'company')},
            },
        ),
    ]
