# Generated by Django 5.2.5 on 2026-06-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_store_options_order_delivery_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='Order Number'),
        ),
    ]
